version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - /share
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
